title: Bot Plays Wordle
description: Bot plays famous Wordle game. Daily Youtube uploads and solution breakdowns.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
collections:
  solutions:
    output: true
plugins:
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-spaceship
jekyll-spaceship:
  processors:
    - mermaid-processor