title: Bot Plays Wordle
description: Bot plays famous Wordle game. Daily Youtube uploads and solution breakdowns.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
url: https://www.botplayswordle.com
collections:
  solutions:
    output: true
plugins:
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-feed
feed:
  collections:
    solutions:
      path: /feed.atom